services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  mainapp-minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: mainapp-minio
    ports:
      - '9003:9000'
      - '9004:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: BGTnhyMJU100
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data: